dist: trusty
addons:
  apt:
    packages:
    - ghostscript
    - poppler-utils
git:
  depth: 5 # use depth 5 to leave enough room for concurrent builds
language: ruby
bundler_args: --path=.bundle/gems --jobs=3 --retry=3 --without=docs
env:
  global:
  - PYGMENTS_VERSION='~> 1.2.0'
  - RGHOST_VERSION='0.9.7'
stages:
- lint
- test
- name: release gem
  if: repo = asciidoctor/asciidoctor-pdf AND tag IS present
script: bundle exec ruby -w $(bundle exec ruby -e "print File.join Gem.bindir, 'rake'") spec
jobs:
  include:
  - stage: lint
    rvm: &newest_ruby 2.7.0
    script: bundle exec rake lint
  - stage: test
  - rvm: jruby-9.2.9.0
  - rvm: jruby-9.1.17.0
  - rvm: *newest_ruby
  - rvm: 2.6.5
  - rvm: 2.5.7
  - rvm: 2.4.9
  - rvm: &oldest_ruby 2.3.8
  - rvm: *oldest_ruby
    env: ASCIIDOCTOR_VERSION=1.5.3
  - rvm: *oldest_ruby
    env: ROUGE_VERSION='~> 2.0.0'
  - stage: release gem
    rvm: *newest_ruby
    script: skip
    deploy:
      provider: rubygems
      gem: asciidoctor-pdf
      api_key: ${RUBYGEMS_API_KEY}
