name: Release
on:
  push:
    tags: ['v*']
jobs:
  activate:
    if: github.repository_owner == 'asciidoctor'
    runs-on: ubuntu-latest
    steps:
    - name: Proceed
      run: echo ok go
  build:
    needs: activate
    runs-on: ubuntu-latest
    env:
      ASCIIDOCTOR_DIAGRAM_VERSION: '~> 2.2'
      PRAWN_GMAGICK_VERSION: '0.0.9'
      PYGMENTS_VERSION: '~> 2.0'
      RGHOST_VERSION: '0.9.7'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
    - name: Install Linux packages
      run: |
        sudo apt-get update
        sudo apt-get install ghostscript poppler-utils libgraphicsmagick1-dev
    - name: Configure Bundler
      run: |
        bundle config --local path .bundle/gems
        bundle config --local without coverage docs lint
    - name: Install dependencies
      run: bundle --jobs 3 --retry 3
    - name: Run tests
      run: bundle exec rake spec
    - name: Publish gem
      uses: dawidd6/action-publish-gem@v1
      with:
        api_key: ${{ secrets.RUBYGEMS_API_KEY }}
